### ISSUE TITLE
Not able to download the theme

### ISSUE THREAD

**Issue by shauryagoel** [eldritch-theme/vivaldi#2]
I am trying to download the theme zip file as mentioned in the README from this [link](https://themes.vivaldi.net/themes/zrnvL65r7L4/versions/2). However, upon opening this page and signing in to my Vivaldi account, I am getting access denied error. However, If I try using [this](https://themes.vivaldi.net/themes/zrnvL65r7L4) everything is working fine.

**Comment by neonvoidx** [comment]
Updated README to correct link
